plugins { id 'com.android.application' }
android {
    namespace 'com.hermes.noir'
    compileSdk 35
    defaultConfig {
        applicationId 'com.hermes.noir'
        minSdk 26
        targetSdk 35
        versionCode 4
        versionName '0.4.0'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildTypes { release { minifyEnabled false } }
}
dependencies { testImplementation 'junit:junit:4.13.2' }
